plot_observed_fx <- function(obs_fx, save = F,
                          pch = 19, cex = 0.2, each_x = 2, each_y = 0.05,
                          alpha = 1, fake_obs = F, print_posterior = F, nsim = 2,
                          epsilon = 0.1, margin_y = 0.05, margin_x = 0.05,
                          x_coord = 40, y_coord = 0.4,
                          grid_rows = 25){
  
  add_empty_plot_with_grid <- function(x_data, y_data, x_label_text,
                                       y_label_text, grid_rows = grid_rows,
                                       margin_y = margin_y,
                                       margin_x = margin_x){
    
    draw_grid <-function(x_coords, y_coords){
      
      for(i in 1:length(x_coords)){
        
        # we draw the i_th vertical line
        segments(x0 = x_coords[i], x1 = x_coords[i],
                 y0 = min(y_coords), y1 = max(y_coords), col=scales::alpha(rgb(0,0,0), 0.1))
      }
      for(i in 1:length(y_coords)){
        # we draw the i_th horizontal line
        segments(x0 = min(x_coords), x1 = max(x_coords),
                 y0 = y_coords[i], y1 = y_coords[i], col=scales::alpha(rgb(0,0,0), 0.1))
      }  
      
    }
    
    xmargin <- (max(x_data, na.rm = T)-min(x_data, na.rm = T))*margin_x
    ymargin <- (max(y_data, na.rm = T)-min(y_data, na.rm = T))*margin_y + 0.025 # Add margin for intervals
    
    new_x <<- round(seq(min(x_data, na.rm = T)-xmargin,
                        max(x_data, na.rm = T)+xmargin, by = each_x),0)
    new_y <<- round(seq(0,
                        max(y_data, na.rm = T)+ymargin, by = each_y),2)
    
    plot(x_data, y_data, xlab=x_label_text, ylab= y_label_text,
         xlim = c(min(new_x),max(new_x)),
         ylim = c(min(new_y),max(new_y)),
         type = 'n', bty = "n", axes = F)
    
    # specify x-axis interval
    axis(side=1, at=round(new_x,0))
    
    ticks <- round(new_y,1)
    axis(side=2, at=ticks)
    
    draw_grid(new_x, new_y)
    
    par(new=TRUE)
  }
  
  # change background color
  par(bg = "white")
  
  m <- which.max(sapply(obs_fx, function(x) max(x$fx)))
  
  add_empty_plot_with_grid(x_data = obs_fx[[m]]$age,
                           y_data = obs_fx[[m]]$fx,
                           x_label_text = "Age",
                           y_label_text = "f(x)",
                           margin_y = margin_y,
                           margin_x = margin_x)
  
  pchs <- c(1,2,5)
  cexs <- c(1.1,0.9,0.9)
  obs_fx_col <- rgb(131/255,75/255,159/255)
  sim_col <- "firebrick2"
  
  # browser()
  
  # Add points to plot
  for(i in 1:length(obs_fx)){
    sml <- smooth.spline(obs_fx[[i]]$fx) 
    sml$y <- ifelse(sml$y<0,0,sml$y) # Adjust negative values generated by spline
    lines(obs_fx[[i]]$age, sml$y, col = obs_fx_col, lty = 2)
    points(obs_fx[[i]]$age, obs_fx[[i]]$fx, pch = pchs[i],
           col = scales::alpha(obs_fx_col, alpha),bty = "n", cex = cexs[i])
  }
  # Legend
  op <- par(family = "sans")
  legend(8, 0.57, legend = c("Hutterites", "Historic Quebec", "Historic France"),
         lwd = c(1,1,1), col = scales::alpha(obs_fx_col, alpha), lty = c(2,2,2),
         pch = c(1,5,2), pt.cex = c(1.3,1,1),
         cex=1.1, bty = "n",
         y.intersp = 1.2,
         x.intersp = 0.5)
  
  if(save){
    save_path <- file.path("..", "write", "plots")
    par(mar = c(4, 4, 0.1, 0.1))
    p <- recordPlot()
    pdf(file.path(save_path, "compare_obs_fx.pdf"), width=9, height=8) 
    print(p)
    dev.off()
  }
  
  
  
}



